### PR TITLE
pymongo connection + twitter 1.1 API 

### LINKED ISSUE #17: The twitter API in chapter 5 is no longer valid
It looks like the twitter API in chapter 5 is no longer valid.  Requesting a new API.

### PR DESCRIPTION
**Pull request by greed2411**
@mikedory 
This is just the same PR with PEP-8 conventions, now my code looks lean and slick. Thanks for pointing that out.

Fixed #17  and #18 

The chapter five - async web services contains the outdated web API of twitter there is another PR but that didn't work for me, so i followed [the new API from twitter](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets) and this [article](http://benalexkeen.com/interacting-with-the-twitter-api-using-python/) to fix those scripts and they worked after some tinkering.

The chapter four contains  - `Connection` which has been changed to `MongoClient` more over [here](https://github.com/dcrosta/professor/issues/13#issuecomment-360423175)

also changed `@tornado.gen.engine` to `@tornado.gen.coroutine` , because of new tornado version.

Also PEP-8

P.S the keys for twitter might work(i committed it by mistake), im not sure. I regenerated mine, if you guys want, you can throw in whatever you want.

### CODE REVIEW

**Comment by mikedory** [comment]
This looks great, thanks @greed2411! 

I removed the keys, and replaced them with `<YOUR-KEY-HERE>` and `<YOUR-SECRET-HERE>`, so hopefully there won't be any confusion for future users reading this. Also, they won't be attached to your account, so you won't get accidental spam. 😜 

We've now got a combination of tabs and spaces (which is a [Python no-no](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces)), but fixing that is beyond the scope of this pull request.

Merging this in — thanks again for doing this!

**Comment by greed2411** [comment]
Thank you so much. I never thought I'd be the one causing the war like this.

Check this tweet 
https://twitter.com/StackSmashing/status/961658232841400320

Thank you for merging my PR, this is my first meaningful contribution in open source.

**Comment by mikedory** [comment]
Ha! It's true — wars have been fought over less. 😆 

And that's great to hear! It's much appreciated on this project, and I'm sure it will be on whatever else you jump in on. Good contributions makes all the difference!

**Comment by greed2411** [comment]
Thank you so much for the good wishes.

**Pull request merged**
